// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Task struct {
	ID            int32
	Code          pgtype.Text
	Name          pgtype.Text
	FrequencyDate pgtype.Text
	FrequencyTime pgtype.Text
	NextRunAt     pgtype.Timestamp
	LastRunAt     pgtype.Timestamp
	MaxRetries    pgtype.Int4
	Status        string
	IsEnabled     bool
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
}

type TasksRun struct {
	ID              int32
	TaskID          pgtype.Int4
	RunAt           pgtype.Timestamp
	FinishedAt      pgtype.Timestamp
	Status          pgtype.Text
	RetryCount      pgtype.Int4
	ErrorMessage    pgtype.Text
	DurationSeconds pgtype.Int4
}
